### ISSUE TITLE
Missing from Maven repo

### ISSUE THREAD

**Issue by simoncomley** [sendinblue/APIv3-java-library#1]
Hi,

I've tried to include this as per instructions and it seems like it's missing from maven repo.

Any idea as to when it will be published.

Thanks
Simon

**Comment by ekta-slit** [comment]
Hi @simoncomley 

It's uploaded today https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22sib-api-v3-sdk%22

Thanks

**Comment by francois92** [comment]
Hi Ekta,

Sending SendEmail with Attachement generates error 
responseBody : {"error":{"status":404,"message":"Invalid route/ method passed","code":"not_found"}}

Sending SendSmtpEmail with Attachement generates error 
sendinblue.ApiException: Internal Server Error

Can you check the problem ?

Thanks
François
