### ISSUE TITLE
emailCampaignsApi.getEmailCampaign(ID) parseException

### ISSUE THREAD

**Issue by lionelbouth** [sendinblue/APIv3-java-library#13]
First, I send an Email campagain as draft in sendinblue without field sechudledAt.

Next, i'm trying to get the campaign using
```
EmailCampaignsApi apiInstance = new EmailCampaignsApi();
GetEmailCampaign result = apiInstance.getEmailCampaign(campaignId);
```
Then I have the error Exception in thread "main" org.threeten.bp.format.DateTimeParseException: Text '' could not be parsed at index 0

It's because you should not serialize the field scheduledAtwith an empty String but NULL

Thanks

**Comment by DienNM** [comment]
I got the same issue

**Comment by amitsendinblue** [comment]
Hi @lionelbouth @DienNM , Please try the latest version 4.0.0 and let us know if you face the same issue again.

Thanks,
Amit Joshi
