### ISSUE TITLE
This version of API compiled for Java 8. May I submit braanch with Java 7 version and get it published as separate artifact.

### ISSUE THREAD

**Issue by crc83** [sendinblue/APIv3-java-library#14]
This version of API compiled for Java 8. May I submit braanch with Java 7 version and get it published as separate artifact.
In exapmle version in this case would be 3.0.1.j7

The only reason to be J8 compatible as far as I understand is Base64 class for encoding decoding.
However I found solution for j7 https://stackoverflow.com/questions/14413169/which-java-library-provides-base64-encoding-decoding

I need this version for no more than year. While we complete migration to latest java

**Comment by crc83** [comment]
I've already did nesessary changes locally.

**Comment by uhausbrand** [comment]
Why aren't you using this change for you locally? There is no reason to deploy an unsupported version for a specific timespan. Just compile your version for yourself and use it where you need to use it. Create a local maven/ivy repository if necessary.

**Comment by VivianaGarces** [comment]
Old thread but which changes did you do?, I have the same need, most of my users have android 4,5,6

**Comment by crc83** [comment]
Sorry. I don't keep changes for so long usually.
@uhausbrand thank you but I know how to distribute artifact inside team. I just thought it might be usefull for other customers as well.

**Comment by Kool-Hussain** [comment]
Hi @crc83 ..!
Now we are not giving support for Java 7. You need to do necessary changes locally. Here is a [link](https://netbeans.apache.org/kb/docs/java/javase-deploy.html), which might help you.
Thanks
