### ISSUE TITLE
Sending email (SendEmail or SendSmtpEmail) with attachement generates Exception

### ISSUE THREAD

**Issue by francois92** [sendinblue/APIv3-java-library#2]
Sending SendEmail with attachement generates error
responseBody : {"error":{"status":404,"message":"Invalid route/ method passed","code":"not_found"}}

Sending SendSmtpEmail with attachement generates error
sendinblue.ApiException: Internal Server Error

**Comment by francois92** [comment]
Does Sendinblue has technical support ?

**Comment by rndbblnn** [comment]
Same issue here, sending the base64 string directly into the HTTP request works fine. I believe it has something to do with the client's byte[] conversion to String

**Comment by francois92** [comment]
François

**Comment by francois92** [comment]
here is a quickstart
[sendinblue_quickstart.zip](https://github.com/sendinblue/APIv3-java-library/files/1782667/sendinblue_quickstart.zip)

**Comment by ekta-slit** [comment]
Hello @francois92,

Thanks for reporting the issue, it has been fixed.
Now for the runtime attachments you just need to pass the byte array of the attachment and it will be encoded to base64 chunk data at our end.

Please refer the sample here https://github.com/sendinblue/APIv3-java-library/blob/master/src/test/java/sendinblue/JsonTest.java

Thanks
