### ISSUE TITLE
Bad Request in logs not very informative

### ISSUE THREAD

**Issue by nicobao** [sendinblue/APIv3-java-library#22]
Hi, 

I use the following code snippet:

```java
public String sendMail(String toEmail, String toName, Long templateId, Object params)
			throws ServiceImplException, NotAllowedException {
			ApiClient defaultClient = Configuration.getDefaultApiClient(); 
			// ApiKeyAuth apiKey = (ApiKeyAuth) defaultClient.getAuthentication("api-key");
			// apiKey.setApiKey(mailerApiKey);
			defaultClient.setApiKey(mailerApiKey);
			SmtpApi apiInstance = new SmtpApi();
			apiInstance.setApiClient(defaultClient);
			// ApiClient defaultClient = Configuration.getDefaultApiClient();
			// defaultClient.setApiKey(mailerApiKey);
			// apiInstance.setApiClient(defaultClient);

			SendSmtpEmail sendEmail = new SendSmtpEmail();

			sendEmail.setTemplateId(templateId);

			List<SendSmtpEmailTo> to = new ArrayList<>();
			SendSmtpEmailTo recipient = new SendSmtpEmailTo();
			recipient.setEmail(toEmail);
			recipient.setName(toName);
			to.add(recipient);
			sendEmail.setTo(to);

			List<SendSmtpEmailBcc> bccList = new ArrayList<>();
			SendSmtpEmailBcc bcc = new SendSmtpEmailBcc();
			bcc.setEmail("support@example.com");
			bccList.add(bcc);
			sendEmail.setBcc(bccList);

			SendSmtpEmailReplyTo replyTo = new SendSmtpEmailReplyTo();
			replyTo.setEmail("support@example.com");
			replyTo.setName("EXAMPLE");
			sendEmail.setReplyTo(replyTo);

			try {
				CreateSmtpEmail result = apiInstance.sendTransacEmail(sendEmail);
				LOGGER.info("[Email] templateId " + templateId + " to " + toEmail + " (" + toName
						+ ") with params + " + params + " successfully sent. Result messageId: "
						+ result.getMessageId());
				return result.getMessageId();
			} catch (ApiException ex) {
				throw new ServiceImplException(
						"[Email] templateId " + templateId + " to " + toEmail + " (" + toName + ") failed", ex);
			}
}

```

and receive an exception `sendinblue.ApiException: Bad Request` without more information. Could it be possible to return more helpful message about what exactly in the message was incorrect? Is it authentification? Is it something else?
How can I log the JSON that's attempting to be sent? (if it can ever get serialized?)

**Comment by nicobao** [comment]
Also, what is the `partner-key` about, please? I don't see anything about this anywhere in your doc, nor in your web app.

**Comment by mourraille** [comment]
> Also, what is the partner-key about, please? I don't see anything about this anywhere in your doc, nor in your web app.
Hi @nicobao , you can remove these code lines. You should only need your Sendinblue api key. Which can be found/generated here: https://account.sendinblue.com/advanced/api

**Comment by mourraille** [comment]
You only want to use these lines:

	   ```
ApiKeyAuth apiKey = (ApiKeyAuth) defaultClient.getAuthentication("api-key");
           apiKey.setApiKey(mailerApiKey);
```

**Comment by nicobao** [comment]
Thank you for the quick reply, but it did not answer my issue.

I was doing what you suggest initially following: https://github.com/sendinblue/APIv3-java-library/blob/master/docs/SmtpApi.md#sendtransacemail
and still got the `Bad Request`. 
Indeed I realize both the solutions presented in your doc (and you suggested) and the one I tried, were correct.

When I try with putting dummy authentication key as follows: `apiKey.setApiKey("test")` I got `sendinblue.ApiException: Unauthorized`, which means I was correctly authenticated when receiving `Bad Request`.

I also discovered how to pretty print better error messages from your `sendinblue.ApiException` class.
You need to manually print "ex.getResponseBody()" as follows:

```java
			try {
				CreateSmtpEmail result = apiInstance.sendTransacEmail(thisEmailWillThrowAnException);
				return result.getMessageId();
			} catch (ApiException ex) {

				throw new ServiceImplException(
						"[Email] templateId " + templateId + " to " + toEmail + " (" + toName + ") failed: "
								+ ex.getResponseBody(),
						ex);
			}

```
so that you get something like:

`io.company.product.exception.ServiceImplException: [Email] templateId null to john.doo@example.com (null) failed: {"code":"missing_parameter","message":"sender is missing"}`

You can also use `ex.getCode()` or `ex.getResponseHeaders()`.
