### ISSUE TITLE
How to send templates Email withou SmtpApi

### ISSUE THREAD

**Issue by GuilhermeLis** [sendinblue/APIv3-java-library#24]
The https://github.com/sendinblue/APIv3-java-library/blob/master/docs/SmtpApi.md#sendTransacEmail is now available, neither the SmtpApi to me imported on java, then how could we send templates now?

**Comment by amitsendinblue** [comment]
Hi @GuilhermeLis, you can send templates using the same API, by providing `templateId` in payload. Please refer the reference [document](https://developers.sendinblue.com/reference#sendtransacemail).

Thanks
