### ISSUE TITLE
OSGI Support

### ISSUE THREAD

**Issue by ChristianLutz** [sendinblue/APIv3-java-library#36]
Hello,

currently we are unable to use this library within an OSGI environment. There are at least two reasons.

1. The lib uses com.google.gson.internal.bind.util.ISO8601Utils in json.java
2. The lib doesn't provide an OSGI MANIFEST.MF file

Workaround:
Create your own project, build a fatjar containing all dependencies.

kind regards

**Comment by Kool-Hussain** [comment]
Hi @ChristianLutz , 
This is an auto-generated code using swagger-codegen. It is difficult for us to provide support for OSGI environment in near future. Apologies,  but for now you will have to go ahead with the work around you suggested.
Thanks..!
