### ISSUE TITLE
How to disable HTTP logs

### ISSUE THREAD

**Issue by lud** [sendinblue/APIv3-java-library#38]
When using this library, there are huge payloads and headers in the standard ouput (those ending with `END POST` or `END HTTP`.

Is there a way to disable those?

Thank you.

**Comment by Kool-Hussain** [comment]
Hi @lud ..!
Would you please share the output where we can see those ending with END POST or END HTTP . It's difficult to understand with limited information.
Thanks.!

**Comment by lud** [comment]
Hi, 

I am not working on this project anymore. I cannot reproduce the case easily. But if I remember correctly, it was simple log of all HTTP interactions from the library basically.

If it's just form me you can close the issue.

Thank you.

**Comment by Kool-Hussain** [comment]
Thankyou for your response.
