### ISSUE TITLE
CreateContact model is missing "ext_id"

### ISSUE THREAD

**Issue by marcmarcet** [sendinblue/APIv3-java-library#48]
Hello!

The CreateContact model seems to be missing the "ext_id" field documented [here](https://developers.brevo.com/reference/createcontact).

**Comment by ArchOrn** [comment]
Is this SDK dead? I am also in need of this feature and it has been months since this issue was created. Brevo has now SDK for Node.js, PHP and Go, but Java is still missing...

**Comment by amitsendinblue** [comment]
Fixed in the latest version brevo_csharp (1.0.0) - https://www.nuget.org/packages/brevo_csharp/
