### ISSUE TITLE
SendSmtpEmail missing tags

### ISSUE THREAD

**Issue by acutus** [sendinblue/APIv3-java-library#8]
`SendSmtpEmail` doesn't seem to support adding `tags`, even though it's documented in v3 api documentation here: https://developers.sendinblue.com/v3.0/reference#sendtransacemail.

**Comment by ekta-slit** [comment]
Hi @acutus 

This parameter has been added in the release https://github.com/sendinblue/APIv3-java-library/releases/tag/v3.0.0

Thanks
